version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: docker
    directories:
      - /build
      - /deb
    schedule:
      interval: weekly
    groups:
      base-images:
        patterns:
          - '*'
